name: Build and Release

on:
  push:
    tags:
      - v*
env:
  PROJECT_NAME: notion-swallow

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - {
              os: ubuntu-latest,
              target: x86_64-unknown-linux-gnu,
              use-cross: false,
              extension: "",
            }
          - {
              os: ubuntu-latest,
              target: aarch64-unknown-linux-gnu,
              use-cross: true,
              extension: "",
            }
          - {
              os: macos-latest,
              target: x86_64-apple-darwin,
              use-cross: false,
              extension: "",
            }
          - {
              os: macos-latest,
              target: aarch64-apple-darwin,
              use-cross: false,
              extension: "",
            }
          - {
              os: windows-latest,
              target: x86_64-pc-windows-msvc,
              use-cross: false,
              extension: .exe,
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target ${{ matrix.job.target }}

      - name: Rename artifacts
        run: |
          mv target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}${{ matrix.job.extension }} ${{ env.PROJECT_NAME }}

      # tar.gzに圧縮
      - name: Compress
        run: |
          tar -czf ${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}.tar.gz ${{ env.PROJECT_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          files: |
            ${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}.tar.gz
